### ISSUE TITLE
Add a real `paste`-function that pastes the content instead of getting it

### ISSUE THREAD

**Issue by pwab** [NikitaBeloglazov/clipman#1]
I just tried pyperclip and this library and was confused by the behavior of the used synonyms. `get` returns the clipboards content and `set` sets it to a new value. What is confusing: `paste` is the same as `get`. I expected a function that can actually `CTRL + V` something. Like this:

- `clipman.paste()`
    - Expected: Pastes the current content of the clipboard
    - Behavior: Does nothing because it only returns a value that is not used in this case
- `clipman.paste("text")`
    - Expected: Pastes "text"
    - Behavior: `TypeError: get() takes 0 positional arguments but 1 was given` (because paste is a synonym of get)

As pyperclip is also not able to actually paste the text somewhere (only working with the contents of the clipboard itself) it could be useful to add such a functionality.

As a workaround I'm using keyboard:

```python
import keyboard
keyboard.press_and_release('ctrl+v')
```

**Comment by NikitaBeloglazov** [comment]
Hello! Thanks for your issue.
Sorry for such a late response, my notifications are broken

`= - = - = - = - = - = -`

> `paste` is the same as `get`

I know this is a little confusing, but in clipman, the `paste()` and `copy()` functions **are only for backward compatibility** with pyperclip, so as not to complicate the work of developers. And these functions will not be changed

They are simply just links to get() and set(), so it is highly recommended to use these methods, especially if the option above confuses you

`= - = - = - = - = - = -`

> I expected a function that can actually CTRL + V something

As i understand, you want clipman to be able to insert text into any running applications on the computer.
This will not be done for a number of reasons:
- This is not the original intent of clipman, it is designed as an API for applications, not as a tool for macros..
- **There is no direct API for such interaction, and doing this by emulating keyboard presses is..**
    - not safe
    - it is very strange as for module
    - it can be placed in two lines as shown above, which does not create the need to add it
    - this is not possible on some operating systems, because they require elevated rights for emulating keyboard

= - = -
For the reasons above, this Issue will be closed **as not planned**
Thank you for your interest in clipman, if you still have questions, ask them.
Have a nice evening!
