### ISSUE TITLE
clip should interpret escape characters or at least have an option to do so

### ISSUE THREAD

**Issue by ferdinandyb** [NikitaBeloglazov/clipman#13]
I would expect that given the string `s = "hello\nworld!"` the output of `print(s)` and pasting the result of `clipman.set(s)`. Or at least have a `clipman.set(s, interpret = True)` to the same effect.

Side note: is there a reason that whatever happens in `clipman.init()` is not executed on `import clipman`?

**Comment by NikitaBeloglazov** [comment]
Hello!

> I would expect that given the string `s = "hello\nworld!"` the output of `print(s)` and pasting the result of `clipman.set(s)`. Or at least have a `clipman.set(s, interpret = True)` to the same effect.

_I may not have clearly understood what you mean,_ but \n escape character work fine for me. If you have problems with it, please show `pip3 show clipman` and `clipman.init(debug=True)` or reformulate/clarify the question

```python3
>>> import clipman
>>> clipman.init() # engine = klipper
>>> clipman.set("hello\nworld!")
>>> print(clipman.get())
hello
world!
>>> clipman.dataclass.engine = "xsel"
>>> clipman.set("hello\nworld!")
>>> print(clipman.get())
hello
world!
>>> clipman.dataclass.engine = "xclip"
>>> clipman.set("hello\nworld!")
>>> print(clipman.get())
hello
world!
>>>
```

---
> Side note: is there a reason that whatever happens in `clipman.init()` is not executed on `import clipman`?

Response to side note: Because
1. With import it is impossible to pass arguments like debug=True
2. This will make it impossible to catch custom exceptions provided by clipman
3. This is too big a process to waste time at the import stage

You can ask the same question to the creators of colorama:))) [(see colorama.init)](https://github.com/tartley/colorama/blob/136808718af8b9583cb2eed1756ed6972eda4975/colorama/initialise.py#L37)

**Comment by ferdinandyb** [comment]
Thanks for quick response! 

This is extremely weird, it now works as you said it should, even though I have a couple of instances on my clipboard history still showing it _didn't_ work just half an hour ago (the top one is what it did now, and the bottom one is what it did when I wrote the issue ...):

![image](https://github.com/NikitaBeloglazov/clipman/assets/6343487/fcdefe95-8068-4440-b717-7ff377dba587)

I am currently unable to repro on both WSL and linux. If you don't mind, I'll test a bit tomorrow and close the issue if I still can't repro it or come back with the specific case where it does not work.

About the side comment: understood :)

**Comment by ferdinandyb** [comment]
Btw, thanks for the tool, you just saved me a ton of time when [putting dataframes](https://github.com/ferdinandyb/dotfiles/blob/9aa809c941cb38e7d094d521e52651d26a333624/.ipython/profile_default/startup/00-startup.py#L22) into markdown documentation.

**Comment by NikitaBeloglazov** [comment]
> This is extremely weird, it now works as you said it should, even though I have a couple of instances on my clipboard history still showing it _didn't_ work just half an hour ago (the top one is what it did now, and the bottom one is what it did when I wrote the issue ...):

Haha, ok:)
If a problem occurs, I’ll wait next time with all the information in hand: `pip3 show clipman`, `clipman.init(debug=True)` and code that don't works

---
> Btw, thanks for the tool, you just saved me a ton of time when [putting dataframes](https://github.com/ferdinandyb/dotfiles/blob/9aa809c941cb38e7d094d521e52651d26a333624/.ipython/profile_default/startup/00-startup.py#L22) into markdown documentation.

Thank youu ♥️
I'm very glad that my project helps someone >ω<

---
###### If no response is received within 7 days, the Issue will be closed

**Comment by ferdinandyb** [comment]
Ok, so this was a complete user error, which came down to the difference between `clipman.set("hello\nworld".__str__())` and `clipman.set("hello\nworld".__repr__())`. The latter preserves the escape characters verbatim. Sorry for the noise.
