### ISSUE TITLE
Error: Clipboard in TTY is unsupported

### ISSUE THREAD

**Issue by neilbaldwin** [NikitaBeloglazov/clipman#20]
Trying to use clipman on headerless Pi and get this error when I try to do:

`clipman.init()`

I have `xsel` and ‘xclip’ installed.

**Comment by NikitaBeloglazov** [comment]
Hello!
TTY doesn't have any features for clipboard, so clipman requires running X11/Wayland/etc for reading clipboard contents. Otherwise, it won't work.

**Comment by neilbaldwin** [comment]
Thanks for replying. That’s disappointing (but not your fault) as I discovered clipman after unsuccessfully trying to get pyperclip working (and having similar issues).

I tried to modify an existing Python project (not mine) to use clipman instead of pyperclip but clearly my issues are a bit deeper and trying to get gtk or x11 or Wayland working is a bit beyond my patience level for this 😂

**Comment by NikitaBeloglazov** [comment]
"Headless" means no graphics, so no X11 or Wayland.
Without X11/Wayland, apps on GTK/Qt (and clipman) will not work, so you need to run X11 or Wayland

But as far as I can see, you are new to Linux, so it might be better to talk with someone in thematic Linux chats. Thanks for your interest to Clipman;)

**Comment by kth8** [comment]
I encountered this as well and came up with this function to only run when its in a X11/Wayland environment or Mac/Windows.
```
def copy_to_clipboard(text):
    if os.environ.get('DISPLAY') is not None or os.environ.get('WAYLAND_DISPLAY') is not None or platform.system() in ['Darwin', 'Windows']:
        clipman.init()
    else:
        return
    try:
        clipman.set(text)
    except clipman.exceptions.ClipmanBaseException as e:
        print(e)
```
I wonder if there is better solution handle this.

**Comment by NikitaBeloglazov** [comment]
@kth8, clipman don't needs re-init every time.
init() is must be called after modules imports

Also, you don't need to check os conditions by yourself, because there is such more conditions as you think.

```python3
import ...
inport clipman
import ...
import ...

try:
    clipman.init()
    clipman_initialized = True
except clipman.exceptions.ClipmanBaseException as e:
    print("Clipboard may not work! Error in clipman: " + str(e))
    clipman_initialized = False
```

```python3
def copy_to_clipboard(text):
    if clipman_initialized is True:
        try:
            clipman.set(text)
        except clipman.exceptions.ClipmanBaseException as e:
            print("Error in clipman: " + str(e))
```

Also, please make sure you give this module a star on Github so that everything works :)

**Comment by NikitaBeloglazov** [comment]
@kth8 also this is soo wrong

https://github.com/kth8/IUT/blob/7ed5b929aab9462da52b28a74737697e3b87a4a4/imgur.py#L12
```python3
print("Clipboard support: Requires wl-clipboard, xclip, xsel or Linux.")
```

Pleaae re-read README for details

**Comment by kth8** [comment]
@NikitaBeloglazov Thanks for the solution. 

Wow embarrassing typo. I meant to say "wl-clipboard, xclip, or xsel on Linux". From what I understand reading the README, no additional dependencies are required with KDE; however, if you're using another desktop environment or window manager, then you'll need either xsel, xclip, or wl-clipboard. Is this correct?

**Comment by NikitaBeloglazov** [comment]
@kth8 Better just place this link: https://github.com/NikitaBeloglazov/clipman#-additional-deps

**Comment by kth8** [comment]
I know either xclip or xsel can be used under X11 but I've never used KDE before so didn't know about its native support. I will link to https://github.com/NikitaBeloglazov/clipman#-support in my README.

**Comment by NikitaBeloglazov** [comment]
@kth8 Ok. Don't forget to give a star for this project! 🌟
