### ISSUE TITLE
[drive-by feedback] Update the GHA workflow for publishing to the PyPI

### ISSUE THREAD

**Issue by webknjaz** [NikitaBeloglazov/clipman#4]
Hey, I noticed you're using my action for uploading to the PyPI, but its version is outdated — https://github.com/pypa/gh-action-pypi-publish/commit/27b31702a0e7fc50959f5ad993c78deac1bdfc29 is 3 years old and doesn't contain modern features.

Follow https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ to get it up-to-date. The GH doc is not as detailed: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi#updating-your-github-actions-workflow.

Action items:
* Update the action version to the recent one
* Drop the use of API tokens and any args in `with:`
* Set up a GitHub environment called `pypi` with required reviews in the repo settings
* Set up OIDC on the PyPI and in the GH workflow job privileges
* Split the jobs for building and uploading, having different privileges for security reasons

**Comment by NikitaBeloglazov** [comment]
Yay! 🎉
- [x] Update the action version to the recent one
- [x] Drop the use of API tokens and any args in with:
- [x] Set up a GitHub environment called pypi with required reviews in the repo settings
- [x] Set up OIDC on the PyPI and in the GH workflow job privileges
- [ ] Split the jobs for building and uploading, having different privileges for security reasons

**Comment by NikitaBeloglazov** [comment]
# ✅ Done!
- [x] Update the action version to the recent one
- [x] Drop the use of API tokens and any args in with:
- [x] Set up a GitHub environment called pypi with required reviews in the repo settings
- [x] Set up OIDC on the PyPI and in the GH workflow job privileges
- [x] Split the jobs for building and uploading, having different privileges for security reasons

### **Thank you very much for your participation in the development of clipman, and in my other projects that use similar technologies! Have a great day!**

**Comment by NikitaBeloglazov** [comment]
✨ Ported to [YTCON](https://github.com/NikitaBeloglazov/ytcon). Thank you again! 🌷
