### ISSUE TITLE
Add fallback for klipper that doesn't require dbus-python

### ISSUE THREAD

**Issue by gotmax23** [NikitaBeloglazov/clipman#5]
I am attempting to use clipman in a virtual environment on a KDE Plasma desktop Wayland session, and am getting the following error:

``` console
$ python
Python 3.12.1 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clipman
>>> clipman.init(debug=True)
init call start
display_server: wayland
current_desktop: KDE
Traceback (most recent call last):
  File "/home/gotmax/dev/antsibull/venv/lib/python3.12/site-packages/clipman/__init__.py", line 158, in detect_clipboard_engine
    import dbus # pylint: disable=import-outside-toplevel
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'dbus'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gotmax/dev/antsibull/venv/lib/python3.12/site-packages/clipman/__init__.py", line 300, in init
    dataclass.engine = detect_clipboard_engine()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gotmax/dev/antsibull/venv/lib/python3.12/site-packages/clipman/__init__.py", line 165, in detect_clipboard_engine
    raise exceptions.AdditionalDependenciesRequired(error_message) from e
clipman.exceptions.AdditionalDependenciesRequired: Please install dbus-python package.
 - Via your system package manager. Possible package names: "python3-dbus-python" or "python3-dbus"
 - Or via PIP: "pip3 install dbus"
>>> import importlib.metadata
>>> importlib.metadata.version("clipman")
'3.1.1'
```

I do not have this issue with pyperclip. I'd prefer not to have to install the dbus-python module, as that requires installing dbus development headers and compiling the wheel locally (dbus-python does not have wheels on PyPI) or using system packages instead of a venv. Would it be possible to fall back to `wl-clipboard` or `xclip` (depending on whether it's a Wayland or X11 session)? For what it's worth, pyperclip treats `klipper` as the last resort and only uses it (by shelling out to `qdbus`) if neither xclip nor wl-clipboard are installed. Thanks!

**Comment by NikitaBeloglazov** [comment]
## ✅ Partically fixed in [v3.1.8](https://github.com/NikitaBeloglazov/clipman/releases/tag/v3.1.8) (0aaede6)

**The klipper interaction system is currently in the early stages of a rewrite, so I made a workaround that solves this problem.
Soon it will be completely rewritten, which will close this Issue complitely**

**Comment by NikitaBeloglazov** [comment]
It looks like I'll leave the idea of rewriting the module in the farthest place, in the box.
As long as it doesn't cause a problem

**Comment by NikitaBeloglazov** [comment]
Oh, i forgot about this issue
Rework of KDE Plasma module & fix for this issue are now in master: https://github.com/NikitaBeloglazov/clipman/commit/ced45d770ce35f963b2d29c5eea8ba84edcece31
