### ISSUE TITLE
clipman uses code from pyperclip without following the license terms

### ISSUE THREAD

**Issue by gotmax23** [NikitaBeloglazov/clipman#6]
clipman uses https://github.com/NikitaBeloglazov/clipman/blob/main/src/clipman/windows.py which was apparently taken from pyperclip. pyperclip is [licensed under the BSD-3-Clause license](https://github.com/asweigart/pyperclip/blob/master/LICENSE.txt) which requires preserving the license text and copyright. clipman does not do this.

**Comment by gotmax23** [comment]
https://github.com/NikitaBeloglazov/clipman/pull/7 is one potential solution.

**Comment by NikitaBeloglazov** [comment]
Hello. Thank you for your feedback. ❣️

Sorry, but your pull request will not be accepted for the following reasons:
- This module was written mostly by myself, relying on answers from Stackoverflow and Microsoft documentation. Yes, I looked at how it was done in pypeclip a little in parallel <sup>(some kind of inspired)</sup>, but this is very far from dependence
- Seems like pypeclip mostly was taken code from Stackoverflow <sup>(see references link in bottom)</sup>, so any copyright is not allowed in this situation
- [BSD-3-Clause license](https://github.com/asweigart/pyperclip/blob/master/LICENSE.txt) is **compatible** with [clipman current license (MPL)](https://github.com/NikitaBeloglazov/clipman/blob/main/LICENSE), therefore add BSD-3-Clause license does not make sense
- I don't want to create an license hell

**For some additional references, see [windows.py#L28](https://github.com/NikitaBeloglazov/clipman/blob/main/src/clipman/windows.py#L28)**
Have a nice day!:)
