### ISSUE TITLE
Invalid placeholder value in pyproject.toml

### ISSUE THREAD

**Issue by gotmax23** [NikitaBeloglazov/clipman#8]
clipman uses an invalid placeholder value for the `version` field in pyproject.toml:

https://github.com/NikitaBeloglazov/clipman/blob/92c21ca271ad611af79a56088cfb574a2899861f/pyproject.toml#L7

This makes it impossible to build a wheel and install the project from source without running extra code to replace the placeholder value.

```
ValueError: invalid pyproject.toml config: `project.version`.
configuration error: `project.version` must be pep440
```

I would recommend setting the placeholder to something like `{last_version}.post0`. You can use `bump2version` to help with this if you'd like or consider setuptools_scm if you prefer to automatically generate versioning metadata from git.

**Comment by NikitaBeloglazov** [comment]
Hello! Thanks you for feedback <3

Clipman already have version marker, which replaces this placeholder.

Just run tags_marker.py
```python3 tags_marker.py```
https://github.com/NikitaBeloglazov/clipman/blob/main/tags_marker.py

But as I see, there are no comments in it. I will fix it today, adding comments and explanations to this file
(and I will look at other issues from you)

_yes, and we should change the name of this file..._

**Comment by gotmax23** [comment]
Thanks for the quick response! Yes, I understand that the placeholder value is updated by that script. The issue is still that it is impossible to build a wheel and install the project from source without running extra code to replace the placeholder value. I cannot, for example, run `pip install git+https://github.com/NikitaBeloglazov/clipman`, because the project has broken metadata. Would you be willing to use a different approach that ensures the default state isn't invalid?

**Comment by NikitaBeloglazov** [comment]
> Thanks for the quick response! Yes, I understand that the placeholder value is updated by that script. The issue is still that it is impossible to build a wheel and install the project from source without running extra code to replace the placeholder value. I cannot, for example, run `pip install git+https://github.com/NikitaBeloglazov/clipman`, because the project has broken metadata. Would you be willing to use a different approach that ensures the default state isn't invalid?

Umm.. what's the point of using `pip install git+https://github.com/NikitaBeloglazov/clipman`?
This doesn't make any sense...

## Just use
- **PyPI version (it is usually synced with the main branch) ([preffered](https://pypi.org/project/clipman/))**
- Use git clone and import it directly
  1\. `git clone https://github.com/NikitaBeloglazov/clipman`
  2\. `cd clipman/src/`
  3\. `python3`
  4\. `import clipman`
- If you really need wheel file, git clone, mark version, and build wheel by yourself

**Comment by gotmax23** [comment]
> Umm.. what's the point of using pip install git+https://github.com/NikitaBeloglazov/clipman?

There are various reasons to install from `git+` with pip, including to get access to an urgent bugfix or to test a PR or feature branch.

Also, `pip install -e .` does not work by default, so I needed to perform extra steps to create an editable install in a virtual environment when hacking on clipman. Then, the git checkout is dirty and I needed to be careful not to commit the edited pyproject.toml.

This placeholder approach diverges from standard practice and makes installing and contributing to the project more difficult.

**Comment by NikitaBeloglazov** [comment]
Actually, i can change `!!{PLACEHOLDER}!!` to `v0.0.0`, and this will no longer break the build, but version updates might be broken with your method of deploy, and using PyPI version or tags_marker.py is still strongly recommended. Or do you have any alternative solution to this problem?

**Comment by gotmax23** [comment]
I would suggest either hard-coding the version and bumping it after each release or using [setuptools-scm](https://pypi.org/project/setuptools-scm/) to calculate the version automatically from git metadata. I'm happy to prepare a patch to enable setuptools-scm if you prefer that approach.

**Comment by NikitaBeloglazov** [comment]
> I'm happy to prepare a patch to enable setuptools-scm if you prefer that approach.

Ok. I'm giving you the green light. I will be looking forward to your pull request :)

**Comment by gotmax23** [comment]
Great! I've submitted https://github.com/NikitaBeloglazov/clipman/pull/14.

**Comment by NikitaBeloglazov** [comment]
Eh. Looks like it is broken in GH Actions

**Comment by NikitaBeloglazov** [comment]
## ✅ Done in [v3.2.3](https://github.com/NikitaBeloglazov/clipman/releases/tag/v3.2.3)
https://github.com/NikitaBeloglazov/clipman/releases/tag/v3.2.3

---
**At some point earlier, I wanted to use setuptools_scm, but I didn't want to delve into it.
It seems I've figured it for now:)**

**Thank you for pull request!** After some time, your works will be ported to [YTCON](https://github.com/NikitaBeloglazov/ytcon) ✨

**Comment by gotmax23** [comment]
Thanks!

**Comment by NikitaBeloglazov** [comment]
✨ Ported to [YTCON](https://github.com/NikitaBeloglazov/ytcon). Thank you again! 🌷
